### ISSUE TITLE
Non-power of 2 Inner-Product Argument 

### ISSUE THREAD

**Issue by suyash67** [KZen-networks/bulletproofs#19]
This Bulletproofs implementation doesn't support inner-product argument generation and verification for inputs of sizes other than powers of 2. How do we use inner-product argument for input sizes not a power of 2? Also, how do we realise it in implementation?

**Comment by omershlo** [comment]
Hi @suyash67. The current implementation indeed support only power of 2. This is mainly because we tried to be as much close to the original paper as possible. 
However, it is easy to add support for proving a number is in any range `a<x<b`. Look here for a clever way to do it: https://github.com/omershlo/simple-bulletproof-js/issues/4. 
If you want to add it to this code - it would be fantastic

**Comment by suyash67** [comment]
Thanks for the inputs @omershlo . I was looking for using a Bulletproofs-like protocol for another problem and not for a range proof. That is the reason I was looking for a non-power of 2 inner-product argument. I could find a way to append 0's to the input vectors in inner product argument, as explained here: https://github.com/dalek-cryptography/bulletproofs/issues/198#issue-377642723

Although inefficient, this seems to work atleast on paper. I am trying to implement it.

Thanks,
Suyash.

**Comment by suyash67** [comment]
Submitted a PR #20 for the same. I guess this issue could now be closed. :)

**Comment by omershlo** [comment]
Thanks you!!!
